script: bundle exec rspec
language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0

env:
  - RAILS_VERSION=3-1-stable
  - RAILS_VERSION=3-2-stable
  - RAILS_VERSION=4-0-stable
  - RAILS_VERSION=master

matrix:
  allow_failures:
    - env: RAILS_VERSION=master
